<?php
/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

?>

<div class="social-icons">
    <p class="brand_title text-uppercase">Loyalty Point : <strong class="text-danger">150</strong></p>
    <p class="text-uppercase py-2">Share :
        <!-- <span class="text-md-end text-start">
            <a href="#" class="icon-button facebook p-1"><i class="fa fa-facebook" aria-hidden="true"></i><span></span></a>
            <a href="#" class="icon-button facebook p-1"><i class="fa fa-instagram" aria-hidden="true"></i><span></span></a>
            <a href="#" class="icon-button twitter p-1"><i class="fa fa-linkedin" aria-hidden="true"></i><span></span></a>
            <a href="#" class="icon-button youtube p-1"><i class="fa fa-youtube" aria-hidden="true"></i><span></span></a>
            <a href="#" class="icon-button pinterest p-1"><i class="fa fa-whatsapp" aria-hidden="true"></i><span></span></a>
        </span> -->
    </p>
</div>
