<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
$helper = $this->helper(\Ecommage\RaffleTickets\Helper\Data::class);
$product = $helper->getCurrentProduct();
?>
<?php if (!$product->getIsCheckRaffle()) :?>
    <div class="breadcrumbs"></div>
    <?php
    $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($viewModel->getJsonConfigurationHtmlEscaped());
    $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['breadcrumbs']);

    ?>
    <script type="text/x-magento-init">
    {
        ".breadcrumbs": {
            "breadcrumbs": <?= /* @noEscape */ $widgetOptions ?>
        }
    }
</script>
<?php else: ?>
    <div class="breadcrumbs" style="display:block;">
        <ul class="items">
            <li class="item home">
                <a href="<?= $block->getUrl($helper->getConfigBreadcrumbsUrl())?>" title="Go to Home Page"><?= $block->escapeHtml(__('Home')) ?></a>
            </li>
            <li class="item product">
                <strong><?= $block->escapeHtml(__($product->getName())) ?></strong>
            </li>
        </ul>
    </div>
<?php endif; ?>