<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Block\Widget\Name;

/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<form class="form form-edit-account new_form_style"
      action="<?= $block->escapeUrl($block->getUrl('ecommage_update_account/update/save')) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">

    <fieldset class="fieldset password" data-container="change-email-password">
        <input type="checkbox" style="display: none" name="change_password"  id="change-password" data-role="change-password" value="1" checked="checked" />
        <div class="field password current required">
            <!-- <label class="label" for="current-password">
                <span><?= $block->escapeHtml(__('Current Password')) ?></span>
            </label> -->
            <div class="control">
                <input type="password" class="input-text " name="current_password" id="current-password"
                       placeholder="<?= $block->escapeHtml(__('Current Password')) ?>"
                       data-input="current-password"
                       autocomplete="off" />
                <input type="checkbox" class="show-password" data-name ="current_password" id="current_password">
                <label for="current_password" class="fa fa-eye-slash"> </label>
            </div>
        </div>
        <div class="field new password required" data-container="new-password">
            <!-- <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label> -->
            <div class="control ">
                <?php $minCharacterSets = $block->getRequiredCharacterClassesNumber() ?>
                <input type="password" class="input-text" name="password" id="password"
                       placeholder="<?= $block->escapeHtml(__('New Password')) ?>"
                       data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                      data-password-min-character-sets="<?= $block->escapeHtml($minCharacterSets) ?>"
                       data-input="new-password"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off" />
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                </div>
                <input type="checkbox" class="show-password" data-name ="password" id="passwords">
                <label for="passwords" class="fa fa-eye-slash"> </label>
            </div>

        </div>

        <div class="field confirmation password required" data-container="confirm-password">
            <!-- <label class="label" for="password-confirmation">
                <span><?= $block->escapeHtml(__('Confirm Password')) ?></span>
            </label> -->
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password_confirmation"
                       placeholder="<?= $block->escapeHtml(__('Confirm Password')) ?>"
                       data-input="confirm-password"
                       autocomplete="off" />
                <input type="checkbox" class="show-password" data-name ="password_confirmation" id="password_confirmations">
                <label for="password_confirmations" class="fa fa-eye-slash"> </label>
            </div>
        </div>

        <div class="field choice" style="display: none" data-bind="scope: 'showPassword'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>

        <div class="actions-toolbar">
            <div class="col-md-10 col-12">
            <div class="internal_page_full_style">
                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>">
                        <span class="btn_style1 btn_style_in">
                            <span>Change Password</span>
                        </span>
                        <div class="content-details fadeIn-left">
                            <span class="btn_style btn_style_in">
                                <span>Change Password</span>
                            </span>
                        </div>
                        </a>
                    </button>
                </div>
                <!-- <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>">
                    <span><?= $block->escapeHtml(__('Change Password')) ?></span>
                </button> -->
            </div>
        </div>
    </fieldset>
</form>
<?php
$scriptString = <<<script
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
      

        dataForm.mage('validation', {
script;
$scriptString .= <<<script
        });

    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php $changeEmailAndPasswordTitle = $block->escapeHtml(__('Change Email and Password')) ?>
<script type="text/x-magento-init">
    {
        " [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($changeEmailAndPasswordTitle) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
<script>
    require(['jquery'], function ($) {
            $("input[type=checkbox].show-password").on('click',function(){
               if ($(this).is(':checked')){
                    $('input[name= '+ $(this).data('name') +']').attr('type','text');
               }else {
                   $('input[name= '+ $(this).data('name') +']').attr('type','password');
               }
            });
    });
</script>
