<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();

$home_url = $block->getBaseUrl();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');

$_item = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());

$product_sku = $_item->getSku();
$product_size = $_item->getResource()->getAttribute('size')->getFrontend()->getValue($_item);

// $product_brand = $_item->getResource()->getAttribute('product_brand')->getFrontend()->getValue($_item);
$product_brand = $_item->getData('product_brand');
$product_brand_arr = explode(",", $product_brand);
$product_brand_html = '';
$count = '0';
if (!empty($product_brand_arr)) {
    foreach ($product_brand_arr as $value) {
        if (!empty($value)) {
            if ($count != '0') {
                $product_brand_html .= ', ';
            }
            $brand_id = $value;
            $query = $connection->select()->from('magetop_brand', ['*'])->where('brand_id = ?', $brand_id);
            $result = $connection->fetchRow($query);
            $brand_name = $result['name'];
            $brand_url_key = $result['url_key'];
            $brand_url = $home_url.'brand/'.$brand_url_key.'.html';
            $product_brand_html .= '<a href="'.$brand_url.'" title="'.$brand_name.'">'.$brand_name.'</a>';
        }
        $count++;
    }
}
?>
<strong class="product-item-name">
    <div class="product-brand">
        <?php echo $product_brand_html;?>
    </div>
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</strong>

<div class="product-item-sku">
    <div class="product_sku">
        <p class="brand_title text-uppercase fw-bold">ITEM NO: <?php echo $product_sku; ?> </p>
    </div>
    <?php if(!empty($product_size)): ?>
    <div class="product_size">
        <p class="brand_title text-uppercase fw-bold">Size: <?php echo $product_size; ?> </p>
    </div>
    <?php endif; ?>
</div>