<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$home_url = $block->getBaseUrl();

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
/** @var \Ecommage\CheckoutCart\Helper\Data $helperCheckRaffle */
$helperCheckRaffle = $this->helper(Ecommage\CheckoutCart\Helper\Data::class);
$checkRaffle = $helperCheckRaffle->checkRaffle();
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
$attribute = $objectManager->create('\Magento\Catalog\Model\ResourceModel\Eav\Attribute');
$abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct');
$_product = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
$product_size = $_product->getResource()->getAttribute('size')->getFrontend()->getValue($_product);
$product_sku = $product->getsku();
$product_price_html = $abstractProductBlock->getProductPrice($_product);

// $product_brand = $_product->getResource()->getAttribute('product_brand')->getFrontend()->getValue($_product);
$product_brand = $_product->getData('product_brand');
$product_brand_arr = explode(",", $product_brand);
$product_brand_html = '';
$count = '0';
if (!empty($product_brand_arr)) {
    foreach ($product_brand_arr as $value) {
        if (!empty($value)) {
            if ($count != '0') {
                $product_brand_html .= ', ';
            }
            $brand_id = $value;
            $query = $connection->select()->from('magetop_brand', ['*'])->where('brand_id = ?', $brand_id);
            $result = $connection->fetchRow($query);
            $brand_name = $result['name'];
            $brand_url_key = $result['url_key'];
            $brand_url = $home_url.'brand/'.$brand_url_key.'.html';
            $product_brand_html .= '<a href="'.$brand_url.'" title="'.$brand_name.'">'.$brand_name.'</a>';
        }
        $count++;
    }
}

// getAppliedRuleIds
$product_applied_offers = [];
$itemAppliedRulesIds = $_item->getAppliedRuleIds();
if ($itemAppliedRulesIds) {
    // 
    $itemAppliedRulesIdsArray = explode(",", $itemAppliedRulesIds);
    foreach ($itemAppliedRulesIdsArray as $key => $value) {
        $rule_id = $value;
        $salesRule = $objectManager->get('Magento\SalesRule\Model\RuleRepository')->getById($rule_id);
        $rule_name = $salesRule->getName();
        $product_applied_offers[] = $rule_name;

    }
}

//
$gift_wrap_available = $_product->getGiftWrappingAvailable();
$quoteId = $_item->getId();
$quote = $objectManager->create('\Magento\Quote\Model\Quote\Item')->load($quoteId);
$gift_message_id = $quote->getGiftMessageId();
$gift_wrap_id = $quote->getGwId();

$gift_wrap_class = '';
if ($gift_wrap_id == null) {
    $gift_wrap_class = "";
}else{
    $gift_wrap_class = "selected";
}
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
                </a>
            <?php else :?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <div class="product-item-brand">
                    <div class="product-brand">
                        <?php echo $product_brand_html;?>
                    </div>
                </div>
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) :?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else :?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <div class="product-item-sku">
                    <p class="product_sku">ITEM NO: <?php echo $product_sku;?></p>
                </div>
                <?php if(!empty($product_size)): ?>
                    <div class="product-item-size">
                        <p class="product_size">SIZE: <?php echo $product_size;?></p>
                    </div>
                <?php endif; ?>
                <?php /*if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) :?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                        <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                    <?php else :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;*/ ?>
                <?php
                $options = $_item->getProduct()->getTypeInstance(true)->getOrderOptions($_item->getProduct());
                if (!empty($options)) {
                    if (isset($options['info_buyRequest']['super_attribute'])) {
                        $super_attribute = $options['info_buyRequest']['super_attribute'];
                        echo '<dl class="item-options">';
                        foreach ($super_attribute as $key => $value) {
                            $attribute_id = $key;
                            $attribute_option_id = $value;

                            $attribute_model = $attribute->load($attribute_id);
                            $attribute_code = $attribute_model->getAttributeCode();
                            $attribute_label = $attribute_model->getFrontendLabel();

                            $_attributeId = $_product->getResource()->getAttribute($attribute_code);
                            if ($_attributeId->usesSource()) {
                                $attribute_option_text = $_attributeId->getSource()->getOptionText($attribute_option_id);
                            }
                            echo '<dt>'.$attribute_label.'</dt>';
                            echo '<dd>'.$attribute_option_text.'</dd>';

                        }
                        echo '</dl>';
                    }
                }
                ?>
                <?php if ($messages = $block->getMessages()) :?>
                    <?php foreach ($messages as $message) :?>
                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) :?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>
        
        <td data-th="<?= $block->escapeHtml(__('Item2')) ?>" class="col item2">
        <?php
        $_options = $block->getOptionList();
         foreach ($_options as $_option) :
         ?>
            <?php if ( array_key_exists('option_type', $_option) && $_option['option_type'] == 'checkbox' && !empty($_product->getIsCheckRaffle())): ?>
                <div class="product-item-sku">
                    <p class="product_sku"><?php echo $_product->getSeries();?></p>
                </div>
                <div class="product-item-sku">
                    <p class="product_sku"><?php echo $_option['value'];?></p>
                </div>
            <?php else: ?>
                <div class="product-item-sku">
                    <p class="product_sku"><?php echo $_option['value'];?></p>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    	</td>

        <?php if ($canApplyMsrp) :?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else :?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <?php $count = $helperCheckRaffle->getPriceAmount($_options); ?>
            <?php if (!$checkRaffle): ?>
                 <?php echo $product_price_html;?>
            <?php endif; ?>
        </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Quantity')) ?>">
            <div class="field qty">
                <div class="control qty">
                <?php  if ($_product->getIsCheckRaffle() != 1): ?>
                    <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                         <span id="<?= $block->escapeHtmlAttr($_item->getId()) ?>-upt" class="decreaseQty">-</span>
                        <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                               name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                               value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                               type="number"
                               size="4"
                               step="any"
                               title="<?= $block->escapeHtmlAttr(__('Quantity')) ?>"
                               class="input-text qty"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"/>
                       <span id="<?= $block->escapeHtmlAttr($_item->getId()) ?>-dec" class="increaseQty">+</span>
                    </label>
                        <?php else :?>
                        <span><?= $block->escapeHtmlAttr($block->getQty()) ?></span>
                    <?php endif; ?>
                </div>
            </div>
            <?php
                if ($checkRaffle) {
                ?>
                <script type="text/x-magento-init">
                        {
                            ".qty": {
                                "Ecommage_CheckoutCart/js/cartItemQtyUpdate": {
                                }
                            }
                        }
                    </script>
                <?php
                }
                ?>
            <?php
            $product_offers = [];
            $product_offer = $_product->getProductOffer();
            $product_offers = unserialize($product_offer);

            if (!empty($product_offers)) {
                $results_offers = [];
                $results_offers = array_diff($product_offers, $product_applied_offers);
                // print_r($results_offers);

                if(!empty($results_offers)) {
                    ?>
                    <?php if (!$checkRaffle): ?>
                    <div class="view_all_offer_content offer-wraper">
                        <div class="offer-button">
                            <a href="javascript:void(0);" class="view_all_offer">View All Offer</a>
                        </div>
                        <div class="view_all_offer_popup offer-content">
                            <div class="box_offers p-4">
                                <ul>
                                    <?php
                                    foreach ($results_offers as $value) {
                                        $product_offer_name = $value;
                                        echo '<li>'.$product_offer_name.'</li>';
                                    }
                                    ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                    <?php
                }
            }
            ?>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp) :?>
                <span class="cart msrp subtotal">--</span>
            <?php else :?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>

        <td class="col actions" data-th="<?= $block->escapeHtml(__('Actions')) ?>">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div> 
        </td>
    </tr>
    <tr>
        <td colspan="5">
            <div class="item-gift-wrap-action <?= $gift_wrap_available ?>">
                <?php if($gift_wrap_available == 1): ?>
                <div class="gift_wrap_option <?php echo $gift_wrap_class;?>">
                    <label><input type="checkbox" class="item_gift_wrap" name="item_gift_wrap" data-cart-item-id="<?php echo $_item->getId();?>" <?php if ($gift_wrap_id != null) { echo "checked='checked'"; } ?>>Gift wrap</label>
                </div>
                <?php endif; ?>
            </div>
        </td>
    </tr>
</tbody>
<?php if (!$checkRaffle): ?>
<script type="text/javascript">
    require(["jquery"], function ($) {
        // increaseQty/decreaseQty
        $('.increaseQty, .decreaseQty').unbind().click(function () {
            let inputElem = $(this).parents('td').find('input');
            let currentQty = inputElem.val();
            if ($(this).hasClass('increaseQty')) {
                inputElem.val(parseInt(currentQty) + parseInt(1));
            } else {
                if (currentQty > 1) {
                    inputElem.val(parseInt(currentQty) - parseInt(1));
                }
            }
            setTimeout([
                $('.cart.actions button[name=update_cart_action]').trigger("click"),
                1000
            ]);
        });

        // view_all_offer
        $('.view_all_offer').unbind().click(function () {
            console.log("sds");
            if($(this).parents('.view_all_offer_content').find('.view_all_offer_popup').hasClass("active")){
                console.log("sds 1");
                $(this).parents('.view_all_offer_content').find('.view_all_offer_popup').removeClass("active");
            }else{
                console.log("sds 2");
                $(this).parents('.view_all_offer_content').find('.view_all_offer_popup').addClass("active");
            }
        });

        // view_all_offer_popup
        $('body').click(function(e) {
            if (!$(e.target).closest('.view_all_offer_content').length){
                $(".view_all_offer_popup").removeClass("active");
            }
        });

        // item_gift_wrap
        $('.item_gift_wrap').unbind().change(function () {
            // console.log("sds");
            var is_gift_wrap = false;
            var cart_item_id = $(this).attr('data-cart-item-id');

            if ($(this).parent().find('input[name=item_gift_wrap]:checked').length > 0) {
                is_gift_wrap = true;
            }else {
                is_gift_wrap = false;
            }

            var base_url = "<?php echo $block->getBaseUrl(); ?>";
            var url = base_url+'customcartrule/giftwrap/index';

            jQuery.ajax({
                url: url,
                type: 'POST',
                // async: false,
                // dataType: 'json',
                data:{
                    'action': 'ajax_overallowance_popup',
                    'cart_item_id': cart_item_id,
                    'is_gift_wrap': is_gift_wrap,
                },
                success: function(data, textStatus, xhr) {
                    console.log("success");
                    console.log(data);
                    $('.cart.actions button[name=update_cart_action]').trigger("click");
                },
                error: function(xhr, textStatus, errorThrown) {
                    //called when there is an error
                    console.log("error");
                }
            });
        });

    });
</script>
<?php endif; ?>
