<?php
/** @var Magento\Framework\View\Element\Template $block */
$helper = $this->helper('Ecommage\OrderRaffle\Helper\Data')
?>
<div class="breadcrumbs">
<ul class="items">
    <li class="item home">
        <a href="<?= $block->getUrl() ?>" title="Go to Home Page"><?= $block->escapeHtml(__('Home')) ?></a>
    </li>
    <li class="item category">
        <a href="<?= $block->getUrl('customer/account/index') ?>" title="<?= $block->escapeHtml(__('My Account')) ?>"><?= $block->escapeHtml(__('My Account')) ?></a>
    </li>
    <li class="item product">
        <strong><?= $block->escapeHtml(__($helper->getBreadcrumb($block->getRequest()->getFullActionName())))?></strong>
    </li>
</ul>
</div>