<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$context = $objectManager->get('Magento\Framework\App\Http\Context');
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);

$customer_is_logged_in = '';
$customer_is_above_age = '';
if($isLoggedIn) {
    // echo "Customer loggedin";
    $customer_is_logged_in = 'yes';

    $customerSession = $objectManager->get('Magento\Customer\Model\Session');  
    $customerData = $customerSession->getCustomer()->getData();
    $customer_id = $customerSession->getCustomer()->getId();
    $shippingAddressId = $customerSession->getCustomer()->getDefaultShipping();

    if (!empty($shippingAddressId)) {
        $addressRepository = $objectManager->get('Magento\Customer\Api\AddressRepositoryInterface');  
        $shippingAddress = $addressRepository->getById($shippingAddressId);
        $customer_dob = $shippingAddress->getCustomAttribute('dateofbirth')->getValue();

        $objDate = $objectManager->create('Magento\Framework\Stdlib\DateTime\DateTime');
        $current_date = $objDate->gmtDate();

        $diff = abs(strtotime($current_date) - strtotime($customer_dob));

        $years = floor($diff / (365*60*60*24));
        $months = floor(($diff - $years * 365*60*60*24) / (30*60*60*24));
        $days = floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));
        // printf("%d years, %d months, %d days\n", $years, $months, $days);
        $age = $years;

        if($age < 21){
            $customer_is_above_age = 'no';
        }else{
            $customer_is_above_age = 'yes';
        }
    }else{
        $customer_is_above_age = '';
    }
}else{
    // echo "Customer loggedout";
    $customer_is_logged_in = 'no';

    $cookie_name = "customer_is_above_age";
    if(!isset($_COOKIE[$cookie_name]) || $_COOKIE[$cookie_name] == 'no') {
        $customer_is_above_age = 'no';
    }else{
        $customer_is_above_age = 'yes';
    }
}
?>

<input type="hidden" id="customer_is_logged_in" value="<?php echo $customer_is_logged_in;?>">
<input type="hidden" id="customer_is_above_age" value="<?php echo $customer_is_above_age;?>">
<div id="age_verification_popup" class="modal custom-modal">
    <div class="custom-modal-wrapper">
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_age_verification_popup')->toHtml(); ?>
    </div>
</div>

<script type="text/javascript">
require(["jquery"], function ($) {
    jQuery(document).ready(function(){
        // product-addtocart-button
        $(document).on('click', '#product-addtocart-button', function(e){
            // e.preventDefault();
            window.addtocart_form = $(this).parents('form');
            var product_in_age = $(this).parents('form').find('input[name="product_in_age"]').val();
            if (product_in_age == 'Yes') {
                var customer_is_logged_in = $("#customer_is_logged_in").val();
                var customer_is_above_age = $("#customer_is_above_age").val();
                if (customer_is_logged_in == 'yes' && customer_is_above_age == 'no') {
                    $("#age_varification_bellow_age_popup").addClass("open");
                    return false;
                }else if (customer_is_logged_in == 'yes' && customer_is_above_age == '') {
                    $("#age_verification_popup").addClass("open");
                    return false;
                }else if (customer_is_logged_in == 'no' && customer_is_above_age == 'no') {
                    $("#age_verification_popup").addClass("open");
                    return false;
                }
            }
        });

        // product-addtocart-form
        $(document).on('click', '.product-addtocart-form button', function(e){
            // e.preventDefault();
            window.addtocart_form = $(this).parents('form');
            var product_in_age = $(this).parents('form').find('input[name="product_in_age"]').val();
            if (product_in_age == 'Yes') {
                var customer_is_logged_in = $("#customer_is_logged_in").val();
                var customer_is_above_age = $("#customer_is_above_age").val();
                if (customer_is_logged_in == 'yes' && customer_is_above_age == 'no') {
                    $("#age_varification_bellow_age_popup").addClass("open");
                    return false;
                }else if (customer_is_logged_in == 'yes' && customer_is_above_age == '') {
                    $("#age_verification_popup").addClass("open");
                    return false;
                }else if (customer_is_logged_in == 'no' && customer_is_above_age == 'no') {
                    $("#age_verification_popup").addClass("open");
                    return false;
                }
            }
        });

        // age_verification_submit
        $(document).on('click', '#age_verification_submit', function(){
            // cookie
            var expDate = new Date();
            expDate.setTime(expDate.getTime() + (24 * 60 * 60 * 1000)); // add 24 hours

            var select_age = $('#age_verification_popup input[name="select_age"]:checked').val();
            if (select_age == 'Above 21') {
                $.cookie('customer_is_above_age', 'yes', { path: '/', expires: expDate });
                $('#customer_is_above_age').val("yes");
                // $('#product_addtocart_form').trigger("submit");
                window.addtocart_form.trigger("submit");
            }else{
                $.cookie('customer_is_above_age', 'no', { path: '/', expires: expDate });
                $('#customer_is_above_age').val("no");
            }

            $("#age_verification_popup").removeClass("open");
        });

        // select_age
        $(document).on('change', '#age_verification_popup input[name="select_age"]', function(){
            var select_age = $('#age_verification_popup input[name="select_age"]:checked').val();
            if (select_age == 'Above 21') {
                $('.select_age_msg').hide();
                $('.select_age_above_21').show();
            }else{
                $('.select_age_msg').hide();
                $('.select_age_bellow_21').show();
            }
        });

    });
});
</script>