<?php
/**
* See COPYING.txt for license details.
 */
/** @var  \Magento\Framework\View\Element\Html\Link $block */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$home_url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$context = $objectManager->get('Magento\Framework\App\Http\Context');
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
$wishlistProvider = $objectManager->get('\Magento\Wishlist\Controller\WishlistProviderInterface');
$customText=$isLoggedIn==true? '<logout>My account</logout>': '<login>Login<login>';
$wishlistItemCounts = 0;
$wishlistClass = '';
?>

<li class="logout_list">
    <a href="<?php echo $home_url; ?>customer/account/index" class="myaccount-header-link text-center"><span class="login_myaccount"><?php echo $customText; ?></span></a>
    <ul class="logout_user" >
    
    <?php if (!empty($isLoggedIn)): ?>
        <?php $currentUserWishlist = $wishlistProvider->getWishlist();
            if ($currentUserWishlist) {
                 $wishlistItems = $currentUserWishlist->getItemCollection();
                 $wishlistItemCounts = $wishlistItems->count();
            }
            $wishlistClass = $wishlistItemCounts? 'wishlist-count':''; ?>

        <div class="list_user">
        <li class="account_linkhead">
    <a href="<?php echo $home_url; ?>customer/account/index" class="whishlist-header-links"><span> Personal Details </span></a>
</li>
<li class="wish_list">
    <a href="<?php echo $home_url; ?>ecommage_update_account/update/change" class="whishlist-header-links"><span>Change Password</span></a>
</li>
<li class="wish_list">
    <a href="<?php echo $home_url; ?>sales/order/history/" class="whishlist-header-links"><span>Order History</span></a>
</li>
<li class="wish_list">
    <a href="<?php echo $home_url; ?>wishlist" class="whishlist-header-links"><span>Wishlist</span></a>
</li>
<li class="border-top" >
    <a href="<?= $block->getUrl('customer/account/logout') ?>" class="myaccount-header-link text-center"><span class="logout_myaccount"><?= $block->escapeHtml(__('Logout')) ?></span></a>
</li>
</div>
<?php endif; ?>
    </ul>
</li>

<li class="<?= $wishlistClass?>">
    <a href="<?php echo $home_url; ?>wishlist" class="whishlist-header-link"><span>Wishlist</span>
        <?php if (!empty($isLoggedIn)): ?>
            
            <span class="wishlist-counter-qty"><?= ($wishlistItemCounts? $wishlistItemCounts:'') ?></span>
        <?php endif;?>
        </a>
</li>

