<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Currency switcher
 *
 * @var \Magento\Directory\Block\Currency $block
 */

// $home_url = $_SERVER['SERVER_NAME'];
$home_url = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]";
?>
<?php if ($block->getCurrencyCount() > 1) : ?>
    <?php $currencies = $block->getCurrencies(); ?>
    <?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher currency switcher-currency" id="switcher-currency<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Currency')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-currency-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <?php
                $current_currency_code = $block->escapeHtml($currentCurrencyCode);
                $current_currency_img = $home_url.'/images/currency/'.strtolower($current_currency_code).'.png';
                ?>
                <strong class="language-<?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                    <img src="<?php echo $current_currency_img;?>" alt="<?php echo $current_currency_code;?>" class="currency-flag-<?php echo $current_currency_code;?>">
                    <span><?= $block->escapeHtml($currentCurrencyCode) ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown" data-target="dropdown">
                <?php foreach ($currencies as $_code => $_name) : ?>
                    <?php if ($_code != $currentCurrencyCode) : ?>
                        <?php
                        $currency_code = $block->escapeHtml($_code);
                        $currency_img = $home_url.'/images/currency/'.strtolower($currency_code).'.png';
                        ?>
                        <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                            <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'>
                                <span><?= $block->escapeHtml($_code) ?></span>
                                <img src="<?php echo $currency_img;?>" alt="<?php echo $currency_code;?>" class="currency-flag-<?php echo $currency_code;?>">
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
