<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

$home_url = $block->getBaseUrl();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$connection = $objectManager->get('Magento\Framework\App\ResourceConnection')->getConnection('\Magento\Framework\App\ResourceConnection::DEFAULT_CONNECTION');
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php
                        $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());
                        // $product_in_age = $_product->getResource()->getAttribute('in_age')->getFrontend()->getValue($_product);


                        $age_limit = 0;
                        $age_limit_category = '';
                        $productConfigHelper = $this->helper('Bdfc\General\Helper\ProductConfig');

                        $ageData = $productConfigHelper->getAgeLimit($_product->getCategoryIds());
                        if (! empty($ageData)) {
                            $age_limit = (isset($ageData['age_limit'])) ? $ageData['age_limit'] : 0;
                            $age_limit_category = (isset($ageData['age_limit_category'])) ? $ageData['age_limit_category'] : '';
                        }                    

                        // $product_brand = $_product->getResource()->getAttribute('product_brand')->getFrontend()->getValue($_item);
                        $product_brand = $_product->getData('product_brand');
                        $product_brand_arr = explode(",", $product_brand);
                        $product_brand_html = '';
                        $count = '0';
                        if (!empty($product_brand_arr)) {
                            foreach ($product_brand_arr as $value) {
                                if (!empty($value)) {
                                    if ($count != '0') {
                                        $product_brand_html .= ', ';
                                    }
                                    $brand_id = $value;
                                    $query = $connection->select()->from('magetop_brand', ['*'])->where('brand_id = ?', $brand_id);
                                    $result = $connection->fetchRow($query);
                                    $brand_name = $result['name'];
                                    $brand_url_key = $result['url_key'];
                                    $brand_url = $home_url.'brand/'.$brand_url_key.'.html';
                                    $product_brand_html .= '<a href="'.$brand_url.'" title="'.$brand_name.'">'.$brand_name.'</a>';
                                }
                                $count++;
                            }
                        }
                        ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <?php
                            echo '<div class="product-badges">';
                                $sql = "SELECT * FROM `product_badges` ORDER BY `badge_id` ASC";
                                $results = $connection->fetchAll($sql);
                                // print_r($results);
                                foreach ($results as $key => $value) {
                                    $badge_id = $value['badge_id'];
                                    $badge_slug = $value['badge_slug'];
                                    $badge_name = $value['badge_name'];

                                    $product_is_badges = $_product->getData($badge_slug);
                                    if ($product_is_badges == true) {
                                        echo '<div class="badges '.$badge_slug.'">';
                                            echo '<img src="/images/badges/'.$badge_slug.'.png" alt="'.$badge_name.'" />';
                                        echo '</div>';
                                    }
                                }
                            echo '</div>';
                            ?>
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <div class="product-brand">
                                        <?php echo $product_brand_html;?>
                                    </div>
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?= $block->getProductPriceHtml($_item, $type) ?>

                                <?= $block->getProductDetailsHtml($_item) ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-inner">
                                        <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                        <form class="product-addtocart-form" data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <input type="hidden" name="product_in_age" value="<?php echo $age_limit > 0 ? "Yes" : "No"; ?>">
                                                            <input type="hidden" name="age_limit_category" value="<?php echo $age_limit_category !='' ? $age_limit_category: "LIQUOR & TOBACCO"; ?>">
                                                            <input type="hidden" name="age_limit" value="<?php echo $age_limit ?>">
                                                            <button type="submit"
                                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                    class="action tocart primary new_add">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        </form>
                                                    <?php else: ?>
                                                        <?php if ($_item->isAvailable()): ?>
                                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                        <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
    <?php if($block->getBlockHtml('formkey')): ?>
    <script type="text/x-magento-init">
    {
        ".block.widget [data-role=tocart-form]": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
    </script>
    <?php endif;?>
<?php endif;?>
