<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<form class="form password forget pb-5"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note fw-bold"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
        <div class="field email required field-float">
            <div class="control">
                <input type="email" 
                    name="email" 
                    alt="email" 
                    id="email_address" 
                    class="input-text" 
                    value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" 
                    data-mage-init='{"mage/trim-input":{}}' 
                    data-validate="{required:true, 'validate-email':true}"
                    placeholder="<?= $block->escapeHtml(__('Email')) ?>"
                />
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar mb-2">
        <div class="primary">
            <button type="submit" class="action submit btn-float" data-hover="Reset My Password">
                <span class="front"><?= $block->escapeHtml(__('Reset My Password')) ?></span>
                <span class="back"><?= $block->escapeHtml(__('Reset My Password')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>
<style>
.btn_style {
    max-width: 360px;
    width: 360px !important;
    min-height: 50px;
    margin: auto !important;
    display: block !important;
    margin-bottom: 30px !important;
    background: #000000 !important;
    outline: none;
    position: relative;
    padding: 10px 10px !important;
    border-radius: 50px !important;
    overflow: hidden;
    border: none !important;
    color: #ffffff !important;
}
</style>