<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_Simpledetailconfigurable
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
/** @var $block \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable*/
$_product    = $block->getProduct();
$_attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes) && !$block->isEnableCpwd()):?>
    <?php foreach ($_attributes as $_attribute): ?>
        <div class="field configurable required">
            <label class="label" for="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>">
                <span><?= $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></span>
            </label>
            <div class="control">
                <select name="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>]"
                        data-selector="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>]"
                        data-validate="{required:true}"
                        id="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId() ?>"
                        class="super-attribute-select">
                    <option value=""><?= /* @escapeNotVerified */ __('Choose an Option...') ?></option>
                </select>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif;?>
<?php if ($_product->isSaleable() && count($_attributes)): ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Bss_Simpledetailconfigurable/js/configurable_control1": {
                "spConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                "jsonChildProduct": <?php echo $block->getJsonChildProductData(); ?>,
                "jsonModuleConfig": <?php echo $block->getJsonModuleConfig(); ?>,
                <?php if (version_compare($block->getMagentoVersion(), '2.2.5', '>=')) : ?>
                "sdcp_classes": {
                    "fullDesc": {
                        "label": "#tab-label-description",
                        "blockContent": "#description"
                    }
                },
                <?php endif; ?>
                "ajaxUrl": "<?php echo $block->getUrl('bss_sdcp/ajax/detail'); ?>",
                "magento21x": <?= version_compare($block->getMagentoVersion(), '2.2.0', '<') ? 1 : 0 ?>,
                "gallerySwitchStrategy": "<?php /* @escapeNotVerified */ echo $block->getVar('gallery_switch_strategy',
    'Magento_ConfigurableProduct') ?: 'replace'; ?>"
            }
        },
        "*" : {
            "Magento_ConfigurableProduct/js/catalog-add-to-cart": {}
        }
    }
</script>
<?php endif;?>
