<?php 
$_helper = $this->helper('Rootways\Megamenu\Helper\Data');
?>
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $_helper->getStoreCss()?>">

<style>
    /* @media (max-width:767px){
.rootmenu > .rootmenu-list .tabmenu .cat-arrow.vertical-tab-click {
    display: inline-block;
    position: absolute;
    right: 0;
    top: 0;
    cursor: pointer;
    width: 30px;
    height: 30px;
}
.rootmenu > .rootmenu-list .tabmenu .cat-arrow.vertical-tab-click::before {
    transform: rotate(45deg);
} 
} */
</style>