<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');
$helper = $this->helper('Ecommage\CheckoutCart\Helper\Data');
/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$product = $block->getPrice()->getProduct();
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>
<?php if ($block->hasSpecialPrice()): ?>
<?php if ($helper->getActionPage()): ?>
        
        <span class="price-discount">
            <?php
            $_price = $block->getPrice()->getProduct()->getPrice();
            $_finalPrice = $block->getPrice()->getProduct()->getFinalPrice();?>
            <?php if($_finalPrice < $_price) :?>
            <?php $_savingPercent = 100 - round(($_finalPrice / $_price)*100);
                $_savingPrice = $_price - $_finalPrice;
               // $savingPrice = number_format((float)$_savingPrice, 2, '.', '');?>
                <span class="price-container">
                    <span class="price">
                        <?= $block->escapeHtml(__('Save %1', $priceHelper->currency($_savingPrice, true, false))) ?>
                    </span>
                </span>

            <?php endif; ?>
        </span>
        <del class="old-price">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Regular Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </del>

        <span class="special-price">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                'display_label'     => __('Special Price'),
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        </span>
<?php else: ?>
        <span class="price-discount">
            <?php
            $_price = $block->getPrice()->getProduct()->getPrice();
            $_finalPrice = $block->getPrice()->getProduct()->getFinalPrice();?>
            <?php if($_finalPrice < $_price) :?>
                <?php $_savingPercent = 100 - round(($_finalPrice / $_price)*100);
                $_savingPrice = $_price - $_finalPrice;
                //$savingPrice = number_format((float)$_savingPrice, 2, '.', '');?>
                <span class="price-container">
                    <span class="price">
                        <?= $block->escapeHtml(__('Save %1',$priceHelper->currency($_savingPrice, true, false))) ?>
                    </span>
                </span>

            <?php endif; ?>
        </span>

        <del class="old-price">
            <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Regular Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </del>
        <span class="special-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>

<?php endif; ?>
<?php else: ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
