<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Create account form template
 *
 * @see \Magento\CustomerCustomAttributes\Block\Form
 */
/* @var $block \Magento\CustomerCustomAttributes\Block\Form */
?>
<?php if ($block->hasUserDefinedAttributes()) : ?>
    <?php if ($block->isShowContainer()) : ?>
    <fieldset class="fieldset">
        <?php endif;?>
        <?php
        $userAttributes = $block->getUserDefinedAttributes();
        $entity = $block->getEntity();
        ?>
        <?php foreach ($userAttributes as $attribute) :?>
            <?php $attributeContent = $block->getAttributeHtml($attribute);?>
            <?php if ($attributeContent) : ?>
                <script>
                    require([
                        'jquery',
                        'mage/translate',
                        'mage/calendar'
                    ], function ($, $t) {
                        $('#cust_dob').calendar({
                            changeMonth: true,
                            dateFormat:'mm/dd/yyyy',
                            changeYear: true,
                            showButtonPanel: true,
                            currentText: $t('Go Today'),
                            closeText: $t('Close'),
                            showWeek: true,
                            showOn: "both",
                            yearRange: '-100:+0', maxDate: new Date(),
                        });
                        $('#cust_dob').val('');
                    })
                </script>
                <?= /* @noEscape */ $attributeContent ?>
            <?php endif;?>
        <?php endforeach;?>
        <?php if ($block->isShowContainer()) : ?>
    </fieldset>
<?php endif;?>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": <?= /* @noEscape */ $block->getViewModel()->getJsComponentsDefinitions($userAttributes, $entity); ?>
                }
            }
        }
    </script>
<?php endif; ?>
